LOCAL_PATH := common_tree_A32U/samsung/a32

BOARD VENDOR := samsung

# INCLUDE PATH 
TARGET_SPECIFIC_HEADER_PATH := $(LOCAL_PATH)/include

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := universal6853
TARGET_NO_BOOTLOADER := false

# Platform
TARGET_BOARD_PLATFORM := MT6853
TARGET_SOC := MT6853

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT_CPU :=
TARGET_CPU_ABI :=
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT :=

# Kernel
BOARD_KERNEL_BASE :=
BOARD_KERNEL_PAGESIZE :=
TARGET_KERNEL_CONFIG := afaneh_a32x_defconfig
